test.sh: add new test.sh.in to run the full pipeline

diff --git a/test.sh.in b/test.sh.in
--- a/test.sh.in
+++ b/test.sh.in
@@ -22,4 +22,14 @@ then
     exit 1
 fi
 
+# Perform a full single end run
+
+${buildir}/pigx-sars-cov2-ww --printshellcmds -s ${srcdir}/tests/settings_se.yaml ${srcdir}/tests/sample_sheet_se.csv
+
+
+if ! test -f "${srcdir}/tests/output/report/index.html"
+then
+    echo "ERROR: Could not find report for single-end run."
+    exit 1
+fi
 
